AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  manage-schedules-with-stepfunction-wait

  Sample SAM Template for manage-schedules-with-stepfunction-wait

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ScheduleTargetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/schedule_target_lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  CalculateWaitTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/calculate_wait_time_lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  ScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaFunction
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: InvokeLambdaFunction
                Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt ScheduleTargetFunction.Arn

  ScheduleGroup:
    Type: AWS::Scheduler::ScheduleGroup
    Properties:
      Name: 'MyOneTimeSchedulesGroup'

  ManageSchedulesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: 'ManageSchedulesWithWaitStateMachine'
      DefinitionUri: state_machine/manage_schedules.asl.json
      DefinitionSubstitutions:
        TargetArn: !GetAtt ScheduleTargetFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn
        ScheduleGroup: !Ref ScheduleGroup
        CalculateWaitTimeLambdaArn: !GetAtt CalculateWaitTimeFunction.Arn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: PassSchedulerRole
              Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - !GetAtt ScheduleRole.Arn
            - Sid: CreateAndDeleteSchedule
              Effect: Allow
              Action:
                - scheduler:CreateSchedule
                - scheduler:DeleteSchedule
              Resource:
                - !Sub
                  - "arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/${scheduleGroup}/*"
                  - scheduleGroup: !Ref ScheduleGroup
            - Sid: InvokeLambdaFunction
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt CalculateWaitTimeFunction.Arn

Outputs:
  ScheduleTargetFunction:
    Description: "Schedule Target Function Arn"
    Value: !GetAtt ScheduleTargetFunction.Arn
  ScheduleGroupArn:
    Description: "Schedule Group Arn"
    Value: !GetAtt ScheduleGroup.Arn
  StateMachine:
    Description: "State Machine ARN"
    Value: !Ref ManageSchedulesStateMachine
